[Integration][Spark] Support adding arbitrary parameters to OpenLineage URL (#425)
* Support Arbitrary Parameters in Lineage URL

Supports extracting parameters from config: spark.openlineage.url
Supports extracting parameters from config: spark.openlineage.url.param.xxx

Users can now pass along additional query / url parameters to the
openlineage url that is used when emitting lineage. This is useful for
passing additional parameters necessary for a non-marquez destination
of OpenLineage metadata.

If using spark.openlineage.url.param.xxx, xxx represents the name of
the url parameter you want to include in the lineage url. Any
configuration variable passed in beginning with spark.openlineage.url.param.
will be used as a url parameter in the lineage url.

These config settings will ignore api_key if it is specified as a url.param
to avoid conflicting with the spark.openlineage.apiKey config.

Signed-off-by: Will Johnson <will@willj.co>

* Adding more idiomatic Java syntax

Signed-off-by: Will Johnson <will@willj.co>

* Even more idiomatic java 8 syntax

Signed-off-by: Will Johnson <will@willj.co>

* [spark] support read/write to kafka (#387)

* adding initial test for spark kafka integration (#279)

* adding initial test for spark kafka integration

Signed-off-by: tomassatka <satka.tomas@gmail.com>

* [spark] Resolves: #280 kafka support

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #280 kafka support

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #280 remove debug line

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #280 javadoc

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #280 review

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #280 review

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* Moved KafkaWriter handling into KafkaRelationVisitor and added support for assign in kafka consumer parsing

Signed-off-by: Michael Collado <mike@datakin.com>

* Add check for hive classes to avoid NoClassDefFoundErrors

Signed-off-by: Michael Collado <mike@datakin.com>

* Fix build for kafka integration (#411)

* Fix integration tests step to run on raw machine to enable docker tests

Signed-off-by: Michael Collado <mike@datakin.com>

* Updated kafka tests to use common version and common reference to kafka package

Signed-off-by: Michael Collado <collado.mike@gmail.com>

* Added reset() call to mock server to avoid results across tests

Signed-off-by: Michael Collado <collado.mike@gmail.com>

* Added String only constructor to HttpError

Signed-off-by: Michael Collado <collado.mike@gmail.com>

* Changed build to copy dependencies and use downloaded jars in Spark containers

Signed-off-by: Michael Collado <collado.mike@gmail.com>

* Fix spark integration test build to use explicit 3.1.2 version

Signed-off-by: Michael Collado <collado.mike@gmail.com>

Co-authored-by: Tomas Satka <61469727+tomassatka@users.noreply.github.com>
Co-authored-by: Michael Collado <mike@datakin.com>
Co-authored-by: Michael Collado <40346148+collado-mike@users.noreply.github.com>
Signed-off-by: Will Johnson <will@willj.co>

* dbt: support dbt build command (#398)

Signed-off-by: Maciej Obuchowski <maciej.obuchowski@getindata.com>
Signed-off-by: Will Johnson <will@willj.co>

* great expectations: pin version to the one supported by airflow operator (#420)

Signed-off-by: Maciej Obuchowski <obuchowski.maciej@gmail.com>
Signed-off-by: Will Johnson <will@willj.co>

* [SPARK] adding output metrics (#361)

* [spark] Resolves: #304 adding task metrics collector

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #304 remove OutputDatasetWithMetadataVisitor.java and deprecated "OutputStatisticsFacet.java"

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #304 add entry in CHANGELOG.md

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #304 add test and fix test

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #304 fix test

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #304 review comments

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* [spark] Resolves: #304 review comments

Signed-off-by: olek <oleksandr.dvornik@gmail.com>

* Fix references to JobMetricsHolder to use singleton, default metric values to null if not present

Signed-off-by: Michael Collado <mike@datakin.com>

Co-authored-by: Michael Collado <mike@datakin.com>
Signed-off-by: Will Johnson <will@willj.co>

* dbt: filter non-test nodes while processing assertions (#422)

Signed-off-by: Maciej Obuchowski <obuchowski.maciej@gmail.com>
Signed-off-by: Will Johnson <will@willj.co>

* Updating OpenLineage spark integration README with new param

Signed-off-by: Will Johnson <will@willj.co>

* Fixing spotless checks

Signed-off-by: Will Johnson <will@willj.co>

Co-authored-by: OleksandrDvornik <oleksandr.dvornik@gmail.com>
Co-authored-by: Tomas Satka <61469727+tomassatka@users.noreply.github.com>
Co-authored-by: Michael Collado <mike@datakin.com>
Co-authored-by: Michael Collado <40346148+collado-mike@users.noreply.github.com>
Co-authored-by: Maciej Obuchowski <maciej.obuchowski@getindata.com>